### ISSUE TITLE
Error when deploying GraphQL

### ISSUE THREAD

**Issue by liznelson** [williamiommi/sanity-plugin-icon-manager#13]
Hey, I love your plugin but I can't seem to deploy this to GraphQL. This is the error I'm hitting. Any help would be greatly appreciated. My sanity.config is really simple. 

```
✖ Generating GraphQL API: production/default

Error: Encountered anonymous inline object "metadata" for field/type "IconManager". To use this field with GraphQL you will need to create a top-level schema type for it. See https://docs.sanity.io/help/schema-lift-anonymous-object-type
```

sanity.config.ts

```
plugins: [deskTool(), visionTool(), IconManager()]
```

package.json

Sanity: 3.23.4

```
  "dependencies": {
    "@sanity/vision": "^3.23.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-is": "^18.2.0",
    "sanity": "^3.23.0",
    "sanity-plugin-icon-manager": "^1.3.0",
    "styled-components": "^6.0.0"
  },
  "devDependencies": {
    "@sanity/eslint-config-studio": "^3.0.1",
    "@types/react": "^18.0.25",
    "eslint": "^8.6.0",
    "prettier": "^3.0.2",
    "typescript": "^5.1.6"
  },
```

**Comment by williamiommi** [comment]
Hey Liz! Thank you for the love for the plugin 😄

I'm not too familiar with GraphQL in general, but the link shared in the error looks promising. 

It is true that the 'metadata' object, where the plugin stores information, is an inline object. The link suggests lifting up inline objects, so probably if I create a specific object called 'icon.manager.metadata,' then the error should be resolved. 
The challenge I see here is understanding whether this is a breaking change or not. I will need some time to test it out.

How do you deploy to GraphQL? Are you using the command present in the following [guide](https://www.sanity.io/docs/graphql#04501f1778aa) (sanity graphql deploy)? Just trying to understand how to test it on my side since I've never used the GraphQL API.

Best,
Will

**Comment by liznelson** [comment]
@williamiommi  Thanks for getting back so quickly!  Yes, I used the sanity graphql deploy command in the guide.

**Comment by williamiommi** [comment]
Hey @liznelson! I just released a fix for the GraphQL deploy. I lifted up all the anonymous nested objects, but the structure of the field remains the same. 
I tested on the GraphQL playground and I'm able to get the nested data inside the metadata subfield.
