### ISSUE TITLE
Feature Proposal: Limit Collections

### ISSUE THREAD

**Issue by OllieJT** [williamiommi/sanity-plugin-icon-manager#15]
First of all, this plugin fills such an important need in Sanity - thank you for the work done so far @williamiommi 

Most projects use icons from one or two collections. To prevent novice users of the CMS from selecting disparate icons from icons that are not within the style of the site - I'd like to limit which collections are shown in the collection tab, and limit the icons shown in the search tab based on collection.

Proposal:
 - Extend the plugin configuration object to allow for an array of icon package names.
 - Filter the list of collections based on the chosen icon package names if defined in the config.
 - Filter the icon search based on the chosen icon package names if defined in the config.
 
 I'm open to submitting a PR for this myself if this kind of feature is welcome.

**Comment by williamiommi** [comment]
Hey @OllieJT!!!
Thank you for the positive feedback; much appreciated 😄 
About the feature request, I like the idea and it makes sense after all. The list of icon sets is huge and overwhelming.
I did some experiments last night and it looks pretty easy to implement the new option via the 'prefixes' parameter.

Let's do some brainstorming about some open points I have:

- Do we need to think about a specific UI when, for any reason (most likely a typo), the filtered collections produce zero results? Maybe just a message like 'no collections available, check your configuration' could be enough.

- Another possible scenario is when, in a list of collections, only one or two are misspelled. In this case, you would only see a subset of collections. Here, I find it more difficult to notify the user because by reading the [documentation](https://iconify.design/docs/api/collections.html), you can also provide just a prefix like 'emojione-', and the API would find two collections: 'emojione-monotone' and 'emojione-v1'. So, I wouldn't have a one-to-one mapping to indicate if some collections are missing among those selected. In this case, I think I will go with the simplest solution at the moment: no error notification at all 😄 

I also have another doubt about possible edge cases with cross-dataset references and multiple workspaces (I'm not too familiar with those concepts). However, in the end, this new feature will be optional, so it won't change the current logic.

Can't give you a specific deadline but I will probably proceed with a first implementation in the next days.

**Comment by OllieJT** [comment]
This sounds great!

I'm not sure if a simpler solution would be to add add another tab with the filtered collections. This would essentially be the collection page with only the selected collections.

Additionally, the config could disable one or both of the tabs.

For example, a config like this would disable the other two tabs, and expose a new tab which is the same as the collections tab, with only the selected collections:
```js
const config = {
	tabs: {
		// search: boolean | undefined
		search: false
		
		// collections: boolean | undefined
		collections: false
		
		// selection: boolean | undefined | string[]
		selection: [ "heroicon-solid", "simple-icon-*" ]
	},
	inlineSvg: true,
	customPalette: [
		{ title: 'Tropical Indigo', hex: '#AB87FF' },
	],
}
```

**Comment by OllieJT** [comment]
Makes sense to me, nice work! And thank you :)
